spring.application.name=ngoma
server.port=8081

spring.datasource.url=jdbc:sqlite:ngoma.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
debug=true